- name: Create Frontend Certificates
  ansible.builtin.command: "step ca certificate --provisioner {{ ansible_fqdn }} --provisioner-password-file /etc/ssh/ssh_host_ed25519_key {{ item.value.host }} /etc/ssl/private/step-ca/haproxy-{{ item.key }}.crt /etc/ssl/private/step-ca/haproxy-{{ item.key }}.crt.key" # noqa: yaml[line-length]
  args:
    creates: "/etc/ssl/private/step-ca/haproxy-{{ item.key }}.crt"
  environment:
    STEPPATH: "/etc/step"
