- name: Add HAProxy 3.0 PPA
  ansible.builtin.apt_repository:
    repo: ppa:vbernat/haproxy-3.0
    state: present

- name: Install HAProxy
  ansible.builtin.package:
    name: 'haproxy=3.0.*'
    state: present

- name: Generate dh params
  community.crypto.openssl_dhparam:
    path: /etc/haproxy/dhparams.pem
    size: 4096
    mode: '0644'
