# TODO: add to unattended upgrades
- name: Add HAProxy 3.0 PPA
  ansible.builtin.apt_repository:
    repo: ppa:vbernat/haproxy-3.0
    state: present

- name: Install HAProxy
  ansible.builtin.package:
    name: 'haproxy=3.0.*'
    state: present

- name: Own HAProxy Dir
  ansible.builtin.file:
    path: /etc/haproxy
    state: directory
    mode: '0755'
    owner: haproxy
    group: haproxy

- name: Own HAProxy Config
  ansible.builtin.file:
    path: /etc/haproxy/haproxy.cfg
    state: file
    mode: "0644"
    owner: haproxy
    group: haproxy
