- name: Bootstrap
  hosts: all
  become: true
  roles:
    - rmb938.bootstrap
  vars:
    step_ca_url: https://cuboid-topi.rmb1993-gmail-com.ca.smallstep.com

- name: HAProxy Base
  hosts: all
  become: true
  roles:
    - haproxy

- name: HAProxy Tier 1
  hosts: tier_1
  become: true
  roles:
    - keepalived
    - tier-1

- name: HAProxy Tier 2
  hosts: tier_2
  become: true
  roles:
    - tier-2
  vars:
    haproxy_hosts:
      hashi-vault:
        host: hashi-vault.haproxy.rmb938.me
        config:
          - balance roundrobin

          - option forwardfor
          - option forwarded

          # Vault Listener Config
          # x_forwarded_for_authorized_addrs=["192.168.23.49", "192.168.23.50"]
          # x_forwarded_for_client_cert_header="X-SSL-Client-Cert"
          # x_forwarded_for_client_cert_header_decoders="BASE64"

          - http-request set-header X-SSL                       %[ssl_fc]
          - http-request set-header X-SSL-Client-Cert           %{+Q}[ssl_c_der,base64]
          - http-request set-header X-SSL-Client-Verify         %[ssl_c_verify]
          - http-request set-header X-SSL-Client-SHA1           %{+Q}[ssl_c_sha1]
          - http-request set-header X-SSL-Client-DN             %{+Q}[ssl_c_s_dn]
          - http-request set-header X-SSL-Client-CN             %{+Q}[ssl_c_s_dn(cn)]
          - http-request set-header X-SSL-Client-Issuer         %{+Q}[ssl_c_i_dn]
          - http-request set-header X-SSL-Client-Not-Before     %{+Q}[ssl_c_notbefore]
          - http-request set-header X-SSL-Client-Serial         %{+Q}[ssl_c_serial,hex]
          - http-request set-header X-SSL-Client-Version        %{+Q}[ssl_c_version]

          - option httpchk GET /sys/health?standbyok=true
          - server hashi-vault-1 hashi-vault-1.rmb938.me:8200 check resolvers nameservers init-addr last,libc,none observe layer7 on-error mark-down ssl verify required ca-file @system-ca # noqa: yaml[line-length]
          - server hashi-vault-2 hashi-vault-2.rmb938.me:8200 check resolvers nameservers init-addr last,libc,none observe layer7 on-error mark-down ssl verify required ca-file @system-ca # noqa: yaml[line-length]
          - server hashi-vault-3 hashi-vault-3.rmb938.me:8200 check resolvers nameservers init-addr last,libc,none observe layer7 on-error mark-down ssl verify required ca-file @system-ca # noqa: yaml[line-length]
