- name: HAProxy Base
  hosts: all
  become: true
  remote_user: ubuntu
  roles:
    - haproxy

- name: HAProxy Tier 1
  hosts: tier_1
  become: true
  remote_user: ubuntu
  roles:
    - keepalived
    - tier-1
  vars:
    haproxy_vip_router_id: 51
    haproxy_http_vip: "192.168.23.46/24"

- name: HAProxy Tier 2
  hosts: tier_2
  become: true
  remote_user: ubuntu
  roles:
    - tier-2
  vars:
    haproxy_hosts:
      hashi-vault:
        host: hashi-vault.haproxy.us-homelab1.hl.rmb938.me
        config:
          - balance roundrobin

          - option forwardfor
          - option forwarded

          # Vault Listener Config
          # x_forwarded_for_authorized_addrs=["192.168.23.49", "192.168.23.50"]
          # x_forwarded_for_client_cert_header="X-SSL-Client-Cert"
          # x_forwarded_for_client_cert_header_decoders="BASE64"

          - http-request lua.clientcert "req"
          - http-response lua.clientcert "res"

          - option httpchk GET /v1/sys/health?standbycode=200

          - server hashi-vault-1 hashi-vault-1.us-homelab1.hl.rmb938.me:8200 check resolvers nameservers init-addr last,libc,none observe layer7 on-error mark-down ssl verify required ca-file @system-ca # noqa: yaml[line-length]
          - server hashi-vault-2 hashi-vault-2.us-homelab1.hl.rmb938.me:8200 check resolvers nameservers init-addr last,libc,none observe layer7 on-error mark-down ssl verify required ca-file @system-ca # noqa: yaml[line-length]
          - server hashi-vault-3 hashi-vault-3.us-homelab1.hl.rmb938.me:8200 check resolvers nameservers init-addr last,libc,none observe layer7 on-error mark-down ssl verify required ca-file @system-ca # noqa: yaml[line-length]

      hashi-consul:
        host: hashi-consul.haproxy.us-homelab1.hl.rmb938.me
        config:
          - balance roundrobin

          - option forwardfor
          - option forwarded

          - option httpchk GET /v1/status/leader
          - server consul-server-1 hashi-consul-1.us-homelab1.hl.rmb938.me:8501 check resolvers nameservers init-addr last,libc,none observe layer7 on-error mark-down ssl verify required ca-file @system-ca # noqa: yaml[line-length]
          - server consul-server-2 hashi-consul-2.us-homelab1.hl.rmb938.me:8501 check resolvers nameservers init-addr last,libc,none observe layer7 on-error mark-down ssl verify required ca-file @system-ca # noqa: yaml[line-length]
          - server consul-server-3 hashi-consul-3.us-homelab1.hl.rmb938.me:8501 check resolvers nameservers init-addr last,libc,none observe layer7 on-error mark-down ssl verify required ca-file @system-ca # noqa: yaml[line-length]
