- name: Configure HAProxy
  ansible.builtin.template:
    src: etc/haproxy/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"
  register: haproxy_config

- name: Start HAProxy
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true

- name: Reload HAProxy # noqa: no-handler
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded
  when: haproxy_config.changed
